apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redemption-api
  namespace: redemption
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: redemption-api-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /prod/redemption/app

