apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redemption-api
  namespace: redemption
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app.kubernetes.io/name: redemption-api

